#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/../config/release.env"

CURRENT_USER="${SUDO_USER:-$USER}"
USER_HOME="$(getent passwd "$CURRENT_USER" | cut -d: -f6)"
PROFILE_DIR="${USER_HOME}/Buildiful/config"
PROFILE_FILE="${PROFILE_DIR}/machine-profile.env"
HOSTNAME_VALUE="$(hostname)"

mkdir -p "${PROFILE_DIR}"

cat > "${PROFILE_FILE}" <<EOP
BUILDIFUL_OS_NAME="${BUILDIFUL_OS_NAME}"
BUILDIFUL_OS_SLUG="${BUILDIFUL_OS_SLUG}"
BUILDIFUL_OS_VERSION="${BUILDIFUL_OS_VERSION}"
BUILDIFUL_OS_CHANNEL="${BUILDIFUL_OS_CHANNEL}"
BUILDIFUL_OS_BASE="${BUILDIFUL_OS_BASE}"
BUILDIFUL_MACHINE_HOSTNAME="${HOSTNAME_VALUE}"
BUILDIFUL_MACHINE_USER="${CURRENT_USER}"
BUILDIFUL_MACHINE_HOME="${USER_HOME}"
EOP

echo "Wrote machine profile to: ${PROFILE_FILE}"
cat "${PROFILE_FILE}"
